Simplify script by using `git status`
Currently we use `git diff`, if we use `git status` along with the flag
`--untracked-files=no` we can drastically simplify the script.  Do it.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,50 +1,26 @@
 #!/usr/bin/env bash
 
+set -e                          # grep failure does not trigger exit.
+
 debug=0                         # Set to 1 to enable debugging, 0 to disable.
-do_check_rs=0
-do_check_ts=0
 
-check_rs_cmd="cargo make check-rs-format"
-check_ts_cmd="cargo make check-ts-format"
-if (( debug == 1 )); then
-    check_rs_cmd="echo check_rs ran"
-    check_ts_cmd="echo check_ts ran"
-fi
-
-git diff --name-only | grep '.rs$' > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-    do_check_rs=1
-fi
-
-git diff --name-only --cached | grep '.rs$' > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-    do_check_rs=1
-fi
-
-git diff --name-only | grep -E '.ts$|.json$|.yml$' > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-    do_check_ts=1
-fi
-
-git diff --name-only --cached | grep -E '.ts$|.json$|.yml$' > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-    do_check_ts=1
-fi
-
-if (( $do_check_rs != 0 )); then
-    eval "$check_rs_cmd"
-    ret=$?
-    if [ $ret -ne 0 ]; then
-       exit $ret
+function check_rs() {
+    if (( debug == 0 )); then
+        cargo make check-rs-format
+    else
+        echo "check_rs ran"
     fi
-fi
+}
 
-if (( $do_check_ts != 0 )); then
-    eval "$check_ts_cmd"
-    ret=$?
-    if [ $ret -ne 0 ]; then
-       exit $ret
+function check_ts() {
+    if (( debug == 0 )); then
+        cargo make check-ts-format
+    else
+        echo "check_ts ran"
     fi
-fi
+}
+
+git status --untracked-files=no --short | grep -E '.rs$' > /dev/null 2>&1 && check_rs
+git status --untracked-files=no --short | grep -E '.ts$|.json$|.yml$' > /dev/null 2>&1 && check_ts
 
 exit 0
